spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "file:///path//to//filesystem" -> store config files in file system
#          search-locations: "classpath:/config"

server:
  port: 8071