spring:
  application:
    name: "configserver"
  profiles:
    active: git # github??? ???
  #    active: native # use for classpath, file

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main # main branch
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///path//to//filesystem" # store config files in file system
#          search-locations: "classpath:/config"

server:
  port: 8071