apiVersion: apps/v1
kind: Deployment # apiVersion과 kind는 항상 고정 kind 값이 바뀌면 에러 발생 (kubernetes가 인식못함)
metadata: # 이 배포에대한 metadata 제공
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: eazybytes/configserver:s12 # 기본적으로 dockerhub에서 찾음, 다른 registry에 있다면 명시해야함
          ports:
            - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver # 이 정보로 위에 configserver와 연동해서 포트를 외부로 노출해준다
  type: LoadBalancer # 포트를 외부로 노출하고 싶을 때 사용
  ports:
    - protocol: TCP
      port: 8071 # 컨테이너 외부로 노출할 포트
      targetPort: 8071 # 컨테이너가 안에서 사용하는 포트
