spring:
  application:
    name: "gatewayserver"

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Enable service discovery, false로하면 routes에 직접 url을 지정해야함
          lower-case-service-id: true # Convert service id to lowercase /ACCOUNTS -> /accounts

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"


#이렇게 해야 debug log가 찍힌다.
logging:
  level:
    com:
      msa:
        gatewayserver: DEBUG